### ISSUE TITLE
Connection timeout on Compute Engine

### ISSUE THREAD

**Issue by anagas** [nodemailer/nodemailer-smtp-transport#29]
Hello,

I use Nodemailer-smtp-transport with sengrid on the google compute engine. 

When i use my code on my pc its works, when i use it on the compute engine it has a timeout. I had a similar problem last time but this was a port issue. I did not change my emailservice.

Error message:

Error: Connection timeout
Monitoring   at SMTPConnection._formatError (/home/testing/node_modules/nodem
ailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:466:15)
Monitoring    at SMTPConnection._onError (/home//testing/node_modules/nodemaile
r-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:452:16)
Monitoring   at SMTPConnection.<anonymous> (/home//testing/node_modules/nodema
iler-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:211:14)
Monitoring  at Timer.listOnTimeout (timers.js:119:15)

   var    transporter = nodemailer.createTransport(smtpTransport({
            service: 'SendGrid',
            port: '2525',
            auth: {
                user: 'xxx',
                pass: 'xxx'
            }
        }));
    
     if(obj, config) {

        var mailOptions = {
            from: config.sendFrom, // sender address
            to: config.sendTo, // list of receivers
            subject: 'Monitoring', // Subject line
            html: '<b>Monitoring</b>' +
            '<p>Sehr geehrte Damen und Herren</p>' +
            '<p> </p>' +
            '<p><b>Fehlermeldung:</b></p>' +
            '<p><b>------------------------------------------------</b></p>' +
            '<p> </p>' +
            '<p><b>Version: ' + config.name +' '+config.version + '</b></p>' +
            '<p><b>Crawling: ' + obj.isNotBlocked + '</b></p>' +
            '<p><b>Fehlerreport: ' + obj.contentErrorRate + '</b></p>' +
            '<p><b>Verbindung : ' + obj.exportUrl + '</b></p>' +
            (obj.queryStatus !== undefined ? ('<p><b></b></p>') : "") +
            '<p><b>------------------------------------------------</b></p>' +
            '<p> </p>' +
            '<p></p>' +
            '<p>Freundliche Grüsse,</p>' +
            '<p> </p>' +
            '<p>Ihr xxx Team</p>'

        };

        transporter.sendMail(mailOptions, function (error, info) {
            if (error) {
                return logger.info(error);
            } else {
                logger.info(config.name + ' :Message send: ', +info.response);
            }

        });
        }

Thanks

**Comment by andris9** [comment]
If you use 'service' option then it overwrites the port option. You should remove service option and replace it with host and port options.

**Comment by anagas** [comment]
Hello andris9,

thanks thats helps me alot and it explains why its works on my local machine.
