### ISSUE TITLE
Document default options

### ISSUE THREAD

**Issue by codepunkt** [nodemailer/nodemailer-smtp-transport#31]
I find the documentation lacking in regards to default options - e.g. does `ignoreTLS`default to true or false, does `secure` default to true or false?

**Comment by andris9** [comment]
I agree, I should list the defaults as well. `ignoreTLS` and most other boolean values are `false` by default, `secure` depends on the context (if you are using port 465, then `secure` is true by default, otherwise it is `false` by default).
