### ISSUE TITLE
If message id is passed with an int value, transport crashes

### ISSUE THREAD

**Issue by pizzurro** [nodemailer/nodemailer-smtp-transport#32]
If a message similar to the following is sent:

``` javascript
{
    "from": "noreply@uphs.upenn.edu",
    "to": ["recipient@gmail.com"],
    "subject": "This should pass",
    "html": "<div>The message</div>",
    "envelope": {
        "from": "test@myemail.com",
        "to": ["recipient@gmail.com"]
    },
    "messageId": 250624
}
```

transport crashes here: https://github.com/nodemailer/nodemailer-smtp-transport/blob/master/lib/smtp-transport.js#L118 

Apps may use the message Id to sync responses with local message caches. In my case, I was testing with my own message ids and inadvertantly used a number.  It was difficult to figure out why the app crashed without an Error thrown.  I think a good improvement would be to throw an Error if message id is defined and is anything other than a string.

**Comment by andris9** [comment]
I agree that it should not throw on such input but the input isn't valid either. A message ID needs to conform to specific format which is "<UNIQUE_ID@DOMAIN>" where UNIQUE_ID is some unique identifier and DOMAIN is a FQDN hostname. If you do not use such a format, then the message-id value most probably gets overriden by some intermediate MTA during transit and you loose your reference.

**Comment by pizzurro** [comment]
Thanks @andris9. I have been using a guid with no change to the message id in response.  In fact, the smtp server doesn't appear to care what I send it as long as it is a string.  

However, I have confirmed that sending a message without a message id sends back an id in the format you described.  If UNIQUE_ID@DOMAIN is the only valid input, shouldn't that format be validated?

**Comment by andris9** [comment]
If the message-id must be corrected or not is decided by the MTA server. Some do nothing about it, some replace it with a valid value only if the value does not conform.

For example, if you try to send an email to a gmail address with such numeric message-id value, this is how the message ends up in the recipients inbox:

Original message:

```
message-id: <1234567890>
```

Message in Gmail inbox:

```
Message-ID: <57dbe8ca.c3c3190a.72107.2e35SMTPIN_ADDED_BROKEN@mx.google.com>
X-Google-Original-Message-ID: <1234567890>
```

**Comment by pizzurro** [comment]
Thanks for the additional info -- I don't have a lot of experience with dealing with MTA servers.  

I see why numeric inputs are not a valid input but it would be nice if the transport didn't blow up if it is given such a value.
